name: Volume Shadow Copy Test
on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  vss-test:
    name: Volume Shadow Copy Test
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version-file: 'go.mod'
        check-latest: true
      id: go
    - name: Install gsudo
      shell: bash
      run: |
        choco install -y --no-progress gsudo
        echo "C:\tools\gsudo\Current" >> $GITHUB_PATH
    - name: Admin Test
      run: gsudo make os-snapshot-tests
    - name: Non-Admin Test
      run: gsudo -i Medium make os-snapshot-tests
    - name: Upload Logs
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
